export const PREDICTION_TERMS = `*Parimutuel Prediction Markets and the Conditions for Payout Validity*

When we speak about prediction markets, we are not merely describing a mechanism for distributing money, but an institutional arrangement for aggregating beliefs under uncertainty. The legitimacy of any payout within such a system depends less on the correctness of an individual prediction and more on the informational environment in which that prediction was made. We therefore begin from the position that payout is not an entitlement attached to accuracy alone, but a consequence of structured disagreement.

In designing the market, we assume that every event admitted into the system exists in a future state that is not yet fully resolved. While absolute uncertainty is neither realistic nor necessary, a non-trivial degree of indeterminacy must persist at the moment participants commit resources. If this condition is absent, the act of prediction collapses into mere recognition, and any subsequent transfer of value becomes analytically unjustifiable.

For this reason, we do not treat market creation as a purely administrative step. Rather, it represents an initial assessment of whether uncertainty is likely to survive long enough for collective judgment to emerge. You may observe that some events, although technically unresolved, carry such overwhelming informational signals that disagreement is unlikely to form. In these cases, restraint is not a limitation of the platform but a deliberate methodological choice.

Participation itself is understood as a signal. We interpret the distribution of commitments not simply as financial input, but as an expression of belief weighted by confidence. A market in which all commitments converge on a single outcome provides little informational content beyond consensus. While consensus has value in other domains, within a prediction market it offers no basis for differential reward. Where opposition fails to materialize, the system is effectively deprived of its comparative function.

As information evolves, so too does the epistemic quality of the market. We recognize that new disclosures, public announcements, or contextual shifts may substantially alter the balance of knowledge before a predefined closing time is reached. In such situations, it becomes necessary to intervene. Closure, when exercised in this manner, should be understood not as interference but as preservation. By fixing participation at a point where uncertainty still existed, we maintain the integrity of earlier commitments and avoid retrospective distortion.

The question of payout arises only after this process has run its course. At resolution, the system evaluates not only which outcome occurred, but whether the market retained sufficient disagreement to justify redistribution. Where meaningful opposition persists, payout proceeds as a function of relative contribution among those aligned with the realized outcome. Where opposition has effectively vanished, the justification for payout weakens correspondingly.

In cases where disagreement collapses entirely, we treat the market as void. This designation does not imply error or misconduct. Rather, it reflects the observation that collective belief converged too decisively for the market to function as an exchange of foresight. In such instances, returning commitments to participants preserves neutrality and avoids attributing value to what is, in effect, shared knowledge.

Throughout this process, we maintain a strict separation between the platform and the predictions expressed within it. We do not assume positions, guarantee outcomes, or supply external funds to sustain payouts. All transfers occur within the closed system defined by participant contributions. This separation is essential not only for financial solvency, but also for conceptual clarity. The platform facilitates expression; it does not participate in belief formation.

Late participation presents a particular challenge. Predictions made after decisive information becomes available risk converting foresight into hindsight. While the boundary between these states is not always sharply defined, we exercise discretion in limiting or invalidating participation that appears to rely on retrospective certainty. Such interventions are guided less by rigid thresholds than by an underlying commitment to fairness and informational symmetry.

You should therefore understand participation as an engagement with uncertainty rather than a pursuit of guaranteed return. Accuracy alone does not ensure profit, just as error does not always imply loss. The market reflects collective reasoning at a specific moment in time, and its outcomes are shaped as much by disagreement as by eventual resolution.

Transparency plays a central role in sustaining trust within this framework. We make visible those elements that materially affect decision-making, including participation levels, stake distribution, and closure conditions. While no system can eliminate ambiguity entirely, openness allows participants to situate their judgments within a shared informational context.

In conclusion, a parimutuel prediction market derives its meaning not from the certainty of outcomes, but from the structure of belief preceding them. When everyone already knows the answer, prediction gives way to acknowledgment, and payout becomes unnecessary. The absence of reward in such cases is not a failure of the system, but evidence that the market has already fulfilled its informational purpose.`;
